<?php

namespace AppBundle\Repository;

/**
 * UriRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UriRepository extends \Doctrine\ORM\EntityRepository
{
}
