<?php

namespace AppBundle\Repository;

/**
 * UriRatingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UriRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
